test-benches:
  S360V0.1:
    test-units:
      -
        module: lan9514
        class: Lan9514
        config:
          name: 'eth1'
          bus_id: 1
          device_id: 2
      -
        module: disk
        class: Disk
        config:
          name: 'uSDCard'
          path: '/dev/mmcblk1'
          size: 64G
          partition_table: 64GB_P5_32GB_P6_32GB
          format:
              -
                partition: 5
                type: ext4
              -
                partition: 6
                type: ext4
      -
        module: command
        class: Command
        config:
          name: 'cmd'
          commands:
              - apt-get update
              - apt-get install cryptsetup

  BLOX-S:
    drivers:
      - module: ps.tenma
        class: Tenma
        config:
          name: PS1
          serial_port: /dev/tty.usbmodem001C284402481

    test-units:
      - module: power.smoketest
        class: SmokeTest
        config:
          name: SmokeTest
          power_supply: PS1
          voltage: 24
          current: 0.5
          max_current: 0.240
          min_current: 0.050
          power_up_delay: 1
          test_time: 2
          leave_state: False

