test-benches:
  S360V0.1:
    unit-tests:
      -
        module: lan9514
        class: Lan9514
        config:
          name: 'eth1'
          bus_id: 1
          device_id: 2
      -
        module: sdcard
        class: SdCard
        config:
          name: 'usdc'
          blk_id: mmcblk1
          blk_size:
             size: 32
             unit: G
          partition_table: 32GB_P5_16GB_P6_16GB.json


