test-benches:
  S360V0.1:
    unit-tests:
      -
        module: lan9514
        class: Lan9514
        config:
          name: 'eth0'
          bus_id: 1
          device_id: 2
      -
        module: mmc
        class: Mmc
        config:
          blk_id: mmcblk1


